### PR TITLE
Better SockJS message identification; fixes #124

### LINKED ISSUE #124: Problem with shinyloadtest::load_runs on remote server
We are trying to setup a load test for a remote server and having issues loading the report.

We are able to record the sessions and run the the recording with several workers on a remote machine, but we are running into problems when we trying to load the runs using:
**df <- shinyloadtest::load_runs("mytest" = "./run1")**  

We are receiving the following error:

**Error: $ operator is invalid for atomic vectors**

We are able to run this on our local dev environment with 1 worker without an issue.  The only difference we see in the recording.log file is the **_w_${WORKER}** and the target types ("Shiny Server or Shiny Server Pro" vs "R/Shiny")

What is the best way to debug this?   Are we missing something?

### PR DESCRIPTION
**Pull request by alandipert**

### CODE REVIEW

File: tests/testthat/test-sockjs-message.R [hunk 1]
```diff
@@ -0,0 +1,16 @@
+context("SockJS message identification")
+
+test_that("SockJS init messages are identified", {
+  # Pre sub-app version of SSP
+  expect_true(isSockjsInit("[\"0|o|\"]"))
```
Comment (schloerke) [inline tests/testthat/test-sockjs-message.R]: Use `isSockjsInitMessage`

(and for calls below)
