### PR TITLE
bug: Give custom labels for all send message commands

### LINKED ISSUE #179: Waterfall labels say `Updated: ` with no other information
The line number is included in the final result, but no `names(message$values)` are present.

https://github.com/rstudio/shinyloadtest/blob/f9089b72060f517a5d08756cb3f2c59eae84a384/R/analysis.R#L173-L184

### PR DESCRIPTION
**Pull request by schloerke**
Fixes #179 

Added support for `WS_RECV`:
* Updated values, Errors, and Input messages; Any combination; Not just Updated values.
* Custom message
* Frozen reactive values
* JS's `window.Shiny.shinyapp.makeRequest()`'s response object
* Notifications
* Modals
* Reloading the app
* Insert/remove ui
* Insert/remove tab
* Tab visibility
* Update query string
* Reset brush

Added support for `WS_SEND`:
* Empty data values: `(Empty update)` rather than `Set: `

From:

```
 [1] "Event 1) Get: Homepage"                                        
 [2] "Event 2) Get: shiny.min.js"                                    
 [3] "Event 3) Get: components.css"                                  
 [4] "Event 4) Get: shiny-sass.css"                                  
 [5] "Event 5) Get: bootstrap.min.css"                               
 [6] "Event 6) Get: bootstrap.bundle.min.js"                         
 [7] "Event 7) Get: font.css"                                        
 [8] "Event 8) Get: memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTS-muw.woff2"
 [9] "Event 9) Get: HI_SiYsKILxRpg3hIP6sJ7fM7PqlPevW.woff2"          
[10] "Event 10) Start Session"                                       
[11] "Event 11) Initialize Session"                                  
[12] "Event 12) Initialize Inputs"                                   
[13] "Event 13) Updated: freeze_bxs_txt, file_output"                
[14] "Event 14) Start File Upload"                                   
[15] "Event 15) File Upload"                                         
[16] "Event 16) Set: btn_error:shiny.action"                         
[17] "Event 17) Updated: "                                           
[18] "Event 18) Set: btn_shinyjsToggle:shiny.action"                 
[19] "Event 19) Updated: "                                           
[20] "Event 20) Set: btn_freezeReactiveValue:shiny.action"           
[21] "Event 21) Updated: "                                           
[22] "Event 22) Updated: "                                           
[23] "Event 23) Set: freeze_bxs"                                     
[24] "Event 24) Updated: freeze_bxs_txt"                             
[25] "Event 25) Set: btn_notification_show:shiny.action"             
[26] "Event 26) Updated: "                                           
[27] "Event 27) Updated: "                                           
[28] "Event 28) Set: btn_notification_close:shiny.action"            
[29] "Event 29) Set: btn_notification_close:shiny.action"            
[30] "Event 30) Updated: "                                           
[31] "Event 31) Updated: "                                           
[32] "Event 32) Set: btn_modal_show:shiny.action"                    
[33] "Event 33) Updated: "                                           
[34] "Event 34) Set: btn_modal_close:shiny.action"                   
[35] "Event 35) Set: btn_modal_close:shiny.action"                   
[36] "Event 36) Updated: "                                           
[37] "Event 37) Set: btn_insert_ui:shiny.action"                     
[38] "Event 38) Updated: "                                           
[39] "Event 39) Updated: "                                           
[40] "Event 40) Updated: "                                           
[41] "Event 41) Set: btn_remove_ui:shiny.action"                     
[42] "Event 42) Set: btn_remove_ui:shiny.action"                     
[43] "Event 43) Updated: "                                           
[44] "Event 44) Updated: "                                           
[45] "Event 45) Set: btn_insert_tab:shiny.action"                    
[46] "Event 46) Updated: "                                           
[47] "Event 47) Updated: "                                           
[48] "Event 48) Set: btn_remove_tab:shiny.action, tabs"              
[49] "Event 49) Set: "                                               
[50] "Event 50) Set: btn_remove_tab:shiny.action"                    
[51] "Event 51) Updated: "                                           
[52] "Event 52) Updated: "                                           
[53] "Event 53) Set: tabs"                                           
[54] "Event 54) Set: btn_toggle_tab:shiny.action"                    
[55] "Event 55) Updated: "                                           
[56] "Event 56) Updated: "                                           
[57] "Event 57) Set: btn_toggle_tab:shiny.action"                    
[58] "Event 58) Updated: "                                           
[59] "Event 59) Updated: "                                           
[60] "Event 60) Set: btn_update_query_string:shiny.action"           
[61] "Event 61) Updated: "                                           
[62] "Event 62) Set: "                                               
[63] "Event 63) Set: btn_reset_brush:shiny.action"                   
[64] "Event 64) Updated: "                                           
[65] "Event 65) Set: does_not_exist"                                 
[66] "Event 66) Set: btn_reload:shiny.action"                        
[67] "Event 67) Updated: "                                           
[68] "Event 68) Get: Homepage"                                       
[69] "Event 69) Stop Session"      
```

To:

```
[1] "Event 1) Get: Homepage"                                              
 [2] "Event 2) Get: shiny.min.js"                                          
 [3] "Event 3) Get: components.css"                                        
 [4] "Event 4) Get: shiny-sass.css"                                        
 [5] "Event 5) Get: bootstrap.min.css"                                     
 [6] "Event 6) Get: bootstrap.bundle.min.js"                               
 [7] "Event 7) Get: font.css"                                              
 [8] "Event 8) Get: memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTS-muw.woff2"      
 [9] "Event 9) Get: HI_SiYsKILxRpg3hIP6sJ7fM7PqlPevW.woff2"                
[10] "Event 10) Start Session"                                             
[11] "Event 11) Initialize Session"                                        
[12] "Event 12) Initialize Inputs"                                         
[13] "Event 13) Updated: freeze_bxs_txt, file_output; Errors: error_output"
[14] "Event 14) Start File Upload"                                         
[15] "Event 15) File Upload"                                               
[16] "Event 16) Set: btn_error:shiny.action"                               
[17] "Event 17) Errors: error_output"                                      
[18] "Event 18) Set: btn_shinyjsToggle:shiny.action"                       
[19] "Event 19) Custom: shinyjs-toggle[txt]"                               
[20] "Event 20) Set: btn_freezeReactiveValue:shiny.action"                 
[21] "Event 21) Freeze: cols"                                              
[22] "Event 22) Input message: freeze_bxs"                                 
[23] "Event 23) Set: freeze_bxs"                                           
[24] "Event 24) Updated: freeze_bxs_txt"                                   
[25] "Event 25) Set: btn_notification_show:shiny.action"                   
[26] "Event 26) Show notification: 0f2bf8aa597c84cc"                       
[27] "Event 27) Custom: shinyjs-disable[btn_notification_show]"            
[28] "Event 28) Set: btn_notification_close:shiny.action"                  
[29] "Event 29) Set: btn_notification_close:shiny.action"                  
[30] "Event 30) Remove notification: 0f2bf8aa597c84cc"                     
[31] "Event 31) Custom: shinyjs-enable[btn_notification_show]"             
[32] "Event 32) Set: btn_modal_show:shiny.action"                          
[33] "Event 33) Show modal"                                                
[34] "Event 34) Set: btn_modal_close:shiny.action"                         
[35] "Event 35) Set: btn_modal_close:shiny.action"                         
[36] "Event 36) Hide modal"                                                
[37] "Event 37) Set: btn_insert_ui:shiny.action"                           
[38] "Event 38) Custom: shinyjs-disable[btn_insert_ui]"                    
[39] "Event 39) Insert UI: #add"                                           
[40] "Event 40) Insert UI: #ui_anchor"                                     
[41] "Event 41) Set: btn_remove_ui:shiny.action"                           
[42] "Event 42) Set: btn_remove_ui:shiny.action"                           
[43] "Event 43) Custom: shinyjs-enable[btn_insert_ui]"                     
[44] "Event 44) Remove UI: #ui_anchor > *"                                 
[45] "Event 45) Set: btn_insert_tab:shiny.action"                          
[46] "Event 46) Custom: shinyjs-disable[btn_insert_tab]"                   
[47] "Event 47) Insert tab: tabs"                                          
[48] "Event 48) Set: btn_remove_tab:shiny.action, tabs"                    
[49] "Event 49) (Empty update)"                                            
[50] "Event 50) Set: btn_remove_tab:shiny.action"                          
[51] "Event 51) Custom: shinyjs-enable[btn_insert_tab]"                    
[52] "Event 52) Remove tab: tabs"                                          
[53] "Event 53) Set: tabs"                                                 
[54] "Event 54) Set: btn_toggle_tab:shiny.action"                          
[55] "Event 55) Hide tab: showhide_tabs"                                   
[56] "Event 56) Input message: btn_toggle_tab"                             
[57] "Event 57) Set: btn_toggle_tab:shiny.action"                          
[58] "Event 58) Show tab: showhide_tabs"                                   
[59] "Event 59) Input message: btn_toggle_tab"                             
[60] "Event 60) Set: btn_update_query_string:shiny.action"                 
[61] "Event 61) Update query string"                                       
[62] "Event 62) (Empty update)"                                            
[63] "Event 63) Set: btn_reset_brush:shiny.action"                         
[64] "Event 64) Reset brush: does_not_exist"                                
[65] "Event 65) Set: does_not_exist"                                       
[66] "Event 66) Set: btn_reload:shiny.action"                              
[67] "Event 67) Reload app"                                                
[68] "Event 68) Get: Homepage"                                             
[69] "Event 69) Stop Session"     
```

### CODE REVIEW

File: R/analysis.R [hunk 1]
```diff
@@ -380,3 +383,198 @@ maintenance_df_ids <- function(df) {
...
+      ))
+    return(paste0("Custom: ", comma_collapse(custom_names)))
+  }
+
+  # Frozen message
+  if (!is.null(message$frozen)) {
+    return(paste0("Freeze: ", comma_collapse(message$frozen$ids)))
+  }
+
+  # Unique Request/Response handler (`window.shiny.makeRequest()` response)
```
Comment (schloerke) [inline R/analysis.R:478]:
```suggestion
  # Unique Request/Response handler (`window.Shiny.shinyapp.makeRequest()` response)
```

File: R/analysis.R [hunk 2]
```diff
@@ -380,3 +383,198 @@ maintenance_df_ids <- function(df) {
...
+
+  # # updateQueryString handler
+  if (!is.null(message$updateQueryString)) {
+    # Contents are too large. We should not display them
+    return("Update query string")
+  }
+
+  # # resetBrush handler
+  if (!is.null(message$resetBrush)) {
+    return("Reset brush")
```
Comment (schloerke) [inline R/analysis.R:562]:
```suggestion
    return(paste0("Reset brush: ", message$resetBrush$brushId))
```

File: R/analysis.R [hunk 3]
```diff
@@ -380,3 +383,198 @@ maintenance_df_ids <- function(df) {
...
+  issue_url <- "https://github.com/rstudio/shinyloadtest/issues/new"
+  cli::cli_warn(
+    c(
+      "!" = "Unknown WS_RECV message",
+      "i" = "Please report this issue to {.url {issue_url} }",
+      "i" = paste0("{.code {msg_json} }")
+    ),
+    # use_cli_format = TRUE,
+    # .frequency = "once",
+    # .frequency_id = paste0("ws_recv_label", names(message))
```
Comment (schloerke) [inline R/analysis.R:576]:
```suggestion
```
